version: '3.7'

services:
    database:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        expose: [3306]
        ports:
            - "3306:3306"
        volumes:
            - ./docker/database/data:/var/lib/mysql

    php-fpm:
        build:
            context: ./docker/php-fpm
        depends_on:
            - database
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://root:@database:3306/main
        volumes:
            - ./:/var/www:cached

    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./var/log:/var/log
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
